# Generated by Django 3.2 on 2021-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
